from collections.abc import Sequence
from pathlib import Path
from typing import final

@final
class Animation:
    def sample(self, index: int, fps: int) -> float: ...
    def sample_many(self, indices: Sequence[int], fps: int) -> list[float]: ...

@final
class ColorAnimation:
    def sample(self, index: int, fps: int) -> str: ...
    def sample_many(self, indices: Sequence[int], fps: int) -> list[str]: ...

@final
class SvgVideo:
    def __len__(self) -> int: ...
    def rgba(self, index: int) -> bytes: ...
    def save_png(self, index: int, path: Path) -> None: ...
    def render(self, path: Path, directory: Path, encoder: str, concurrency: int) -> None: ...

def compile_animation(keyframes: list[tuple[float, float, float, float, str]]) -> Animation: ...
def compile_color_animation(
    keyframes: list[tuple[float, float, str, str, str]],
) -> ColorAnimation: ...
def compile_video(
    width: int,
    height: int,
    fps: int,
    frames: Sequence[str],
    load_system_fonts: bool,
    fonts: Sequence[str | Path] = (),
) -> SvgVideo: ...

@final
class SceneVideo:
    def __len__(self) -> int: ...
    def rgba(self, index: int) -> bytes: ...
    def save_png(self, index: int, path: Path) -> None: ...
    def audio_samples(self) -> bytes: ...
    def render(
        self, path: Path, directory: Path, encoder: str, concurrency: int, bitrate: int
    ) -> None: ...

def compile_scene(plan: str) -> SceneVideo: ...
